Homework 1.5
h001y/react-course pull request #9
Opened 2020-12-28 00:43 UTC by h001y

Work with airtable API. Api KEY inside in const API_TOKEN .

2021-01-12 07:29 UTC, index01d requested changes

2021-01-12 07:29 UTC, index01d commented on src/BookCard.js
>  class BookCard extends React.Component {
Стоит выделить в карточке отдельные компоненты следуя https://reactjs.org/docs/thinking-in-react.html ([на русском](https://ru.reactjs.org/docs/thinking-in-react.html)). Ниже подсветил почему

2021-01-12 07:29 UTC, index01d commented on src/BookCard.js
> +                    <div class='w3-row'>
Отдельный компонент `<Name>` поможет понять относится ли этот блок к названию книги или нет. В общем компоненте сложновато определить назначение блока с произвольным классом

2021-01-12 07:29 UTC, index01d commented on src/BookCard.js
> +                        <div className={classes.simpleRow}>Subscribers: {subscribers}</div>
выделение отдельного компонента
`<SimpleRow label='Subscribers'>{subscribers}</SimpleRow>`
избавит от дублирования класса  и улучшит читаемость

2021-01-12 07:29 UTC, index01d commented on src/BookCard.js
>      progress: 'w3-row w3-padding m2',
обращаю внимание на то, что классы language, progress и pageNum не отличаются. Логичнее было бы разместить конкретные классы в компоненте Row и избавиться от объекта classes, как концепции. Искать запись в общем объекте всякий раз, когда нужно внести изменение во внешний вид того или иного компонента может быть довольно утомительно.

2021-01-12 07:29 UTC, index01d commented on src/BookContainer.js
> +const FullUrlApi = 'https://api.airtable.com/v0/appnTJaLKZEKO39K2/Books?api_key=keyxVH3YtgGxjTv8g';
похоже, что нигде не используется

2021-01-12 07:29 UTC, index01d commented on src/BookContainer.js
> +const httpClient = axios.create({
инициализацию клиента и константу API_TOKEN можно вынести в отдельный модуль

2021-01-12 07:29 UTC, index01d commented on src/BookContainer.js
> +import * as _ from 'lodash'
лучше импортировать конкретные зависимости из lodash, чтобы оставить возможность сократить размер пакета при сборке. Кроме того, это упростит анализ зависимостей, если будет принято решение устранить lodash из проекта

`import get from 'lodash/get'` или хотя бы `import { get } from 'lodash'` лучше чем `import * as _`

2021-01-12 07:29 UTC, index01d commented on src/BookContainer.js
> +        httpClient.get('/Books?api_key='+API_TOKEN , {
api_key можно переместить ниже в params, чтобы избежать низкоуровневой конкатенации и разнообразия в способах определения query-параметров

2021-01-12 07:29 UTC, index01d commented on src/BookContainer.js
> +                return stringify(params, { arrayFormat: 'brackets' })
можно использовать по аналогии вариант стрелочной функции с возвращаемым значением 

```js
paramsSerializer: (params) => stringify(params, { arrayFormat: 'brackets' })
```

2021-01-18 07:53 UTC, h001y commented on src/BookCard.js
> +                    <div class='w3-row'>
Выделил компонент BookName и вынес BookCard в отдельную папку

2021-01-18 08:12 UTC, h001y commented on src/BookCard.js
> +                        <div className={classes.simpleRow}>Subscribers: {subscribers}</div>
Выделил компонент SimpleRow

2021-01-18 08:34 UTC, h001y commented on src/BookCard.js
>      progress: 'w3-row w3-padding m2',
Убрал константу classes из BookCard -> все класы фреймворка добавил к элементам

2021-01-18 09:33 UTC, h001y commented on src/BookContainer.js
> +const FullUrlApi = 'https://api.airtable.com/v0/appnTJaLKZEKO39K2/Books?api_key=keyxVH3YtgGxjTv8g';
Убрал

2021-01-18 15:37 UTC, h001y commented on src/BookContainer.js
> +import * as _ from 'lodash'
исправил на import { zip, zipObject } from 'lodash'

2021-01-18 15:43 UTC, h001y commented on src/BookContainer.js
> +                return stringify(params, { arrayFormat: 'brackets' })
исправил

2021-01-19 08:58 UTC, index01d approved these changes

2021-01-19 08:58 UTC, index01d commented on src/bookCard/BookName.js
> +        <>
фрагмент здесь кажется лишним. Возвращается только один элемент div, значит объединять во фрагмент нечего

2021-01-19 08:58 UTC, index01d commented on src/bookCard/BookName.js
> +    const { name } = props;
можно деструктурировать в сигнатуре функции компонента
```
const BookName = ({ name }) => {
```

2021-01-19 08:58 UTC, index01d commented on src/bookCard/SimpleRow.js
> +    const { label, rowDescription, rowDynamic } = props;
аналогично можно деструктурировать в сигнатуре функции компонента и фрагмент лишний

2021-01-21 09:23 UTC, h001y commented on src/bookCard/BookName.js
> +        <>
исправил

2021-01-21 09:24 UTC, h001y commented on src/bookCard/BookName.js
> +    const { name } = props;
исправил

2021-01-21 09:24 UTC, h001y commented on src/bookCard/SimpleRow.js
> +    const { label, rowDescription, rowDynamic } = props;
исправил

2021-01-21 09:25 UTC, merged